version: "3.8"
services:
  backend:
    env_file:
      - .env
    container_name: todo-app
    depends_on:
      postgres:
        condition: service_started
    ports:
      - "8080:8080"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs:/out/configs
      - .env
    restart: always

  postgres:
    env_file:
      - .env
    image: postgres:14
    container_name: todo-db
    ports:
      - "5438:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./myschema/000001_init.up.sql:/docker-entrypoint-initdb.d/initdb.sql
    restart: always