version: '3.8'

services:
  backproject-app:
    build: ./
    command: ./wait-for-postgres.sh  db ./backproject-app
    ports:
      - 8001:8001
    depends_on:
      - postgres
    environment:
      - DB_PASSWORD=qwerty

  postgres:
    restart: always
    image: postgres:latest
    volumes:
      - ./.database/postgres/data/:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5436:5432